[features]
seeds = false
skip-lint = false

[programs.localnet]
forward = "EA1L67z5Zraz8v8g1MhNKAKaMQkmFP1SprKaVv2gRXxP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
